#!/bin/bash

top=anspwm
cfgfile=fourmods


quartus_map --read_settings_files=on --write_settings_files=off $top -c $cfgfile 
quartus_fit --read_settings_files=off --write_settings_files=off $top -c $cfgfile 
quartus_asm --read_settings_files=off --write_settings_files=off $top -c $cfgfile 
quartus_sta $top -c $cfgfile
quartus_eda --read_settings_files=off --write_settings_files=off $top -c $cfgfile 
#quartus_npp $top -c $cfgfile --netlist_type=sgate
#quartus_npp $top -c $cfgfile --netlist_type=atom_fit
